# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
#COPY requirements.txt ./
#RUN pip install --no-cache-dir -r requirements.txt

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV NAME World

# Run both scripts when the container launches
CMD ["python", "-c", "import GoogleMapsEndPoint_Filtered as filtered; import GoogleMapsEndPoint_raw as raw; filtered.main(); raw.main()"]